### ISSUE TITLE
TruePeak limiter

### ISSUE THREAD

**Issue by actionless** [lsp-plugins/lsp-plugins-limiter#2]
There are several ways of determining "True" peak amplitude in broadcasting.
And today's most popular standard is EBU-R.
(there is even a library with MIT license which already implements the code: https://github.com/jiixyj/libebur128).

From the point of the UI, i think it could be 2 controls - checkbox for toggling between normal and TruePeak modes, and in case TruePeak mode enabled - the window size for measurement.

**Comment by sadko4u** [comment]
Moved the feature request here: https://github.com/sadko4u/lsp-plugins/issues/333
